name: Build BL2 & FIP - X60 New / X30E Pro

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      flash_size:
        description: Flash size in megabytes (MB)
        default: "128"
        required: true
      model:
        description: Device model (x60-new / x30e-pro)
        default: "x60-new"
        required: true

jobs:
  Build-bl2-fip:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v6

    - name: Create env variables 
      run: |
        echo "Create env variables based on flash size input..."
        echo "Flash size input: ${{ inputs.flash_size }}MB"
        if [ ${{ inputs.flash_size }} -eq 128 ]; then
          echo "nand_type=spim:2k+64" | tee -a $GITHUB_ENV
          echo "suffix=" | tee -a $GITHUB_ENV
        elif [ ${{ inputs.flash_size }} -eq 256 ]; then
          echo "nand_type=spim:2k+128" | tee -a $GITHUB_ENV
          echo "suffix=_256m" | tee -a $GITHUB_ENV
          echo "release_note=(for 256MB flash)" | tee -a $GITHUB_ENV
          echo "vertag_256m= 256MB Flash" | tee -a $GITHUB_ENV
          sed -i '/_NAND_TYPE_2K_/s/64/128/' atf-mtk/configs-*/mt7986_ruijie_rg-${{inputs.model}}*_defconfig
        else
          echo "Invalid flash size. Please enter either 128 or 256."
          exit 1
        fi

        cfg=atf-mtk/configs-ubi/*-${{inputs.model}}-ubi_defconfig
        ubiaddr=$(grep "^OVERRIDE_UBI_START_ADDR" ${cfg} | cut -d'=' -f2)
        echo "ubi_addr=$ubiaddr" | tee -a $GITHUB_ENV

        echo "Setting source code versions..."
        echo "uboot_ver=uboot-mtk-20250711" | tee -a $GITHUB_ENV
        echo "atf_ver=atf-20260123" | tee -a $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get -yq update
        sudo apt-get -yq install gcc-aarch64-linux-gnu build-essential device-tree-compiler nodejs

        mkdir outputs

    - name: Build bl2 & fip - UBI
      run: |
        echo "Building bl2 & fip for UBI variant..."
        git clone --depth 1 https://github.com/Yuzhii0718/bl-mt798x-dhcpd.git fip

        cd fip
        cp ../uboot-mtk/configs-ubi/mt7986_ruijie_rg-${{inputs.model}}-ubi_defconfig ${{ env.uboot_ver }}/configs-ubi/
        cp ../atf-mtk/configs-ubi/mt7986_ruijie_rg-${{inputs.model}}-ubi_defconfig ${{ env.atf_ver }}/configs-ubi/

        if [ ! -z "$vertag_256m" ]; then
          export BUILD_STRING="$vertag_256m"
        fi
        make BOARD=ruijie_rg-${{inputs.model}}-ubi VERSION=SP2 VARIANT=UBI MULTI_LAYOUT=0 FIXED_MTDPARTS=0 UBIMNG=1

        cp output/fip-mt7986_ruijie_rg-${{inputs.model}}*ubi*.bin ../outputs/ubi-yuzhii-fip-${{inputs.model}}.bin
        cp output/bl2-mt7986_ruijie_rg-${{inputs.model}}*ubi*.img ../outputs/ubi-yuzhii-bl2-${{inputs.model}}${{ env.suffix }}.img

    - name: Build bl2 & fip - NONMBM
      run: |
        echo "Building bl2 & fip for NONMBM variant..."
        cd fip
        make clean && rm -rf output/*
        cp ../uboot-mtk/configs-nonmbm/mt7986_ruijie_rg-${{inputs.model}}-max_defconfig ${{ env.uboot_ver }}/configs-nonmbm/
        cp ../atf-mtk/configs-nonmbm/mt7986_ruijie_rg-${{inputs.model}}-max_defconfig ${{ env.atf_ver }}/configs-nonmbm/

        if [ ! -z "$vertag_256m" ]; then
          export BUILD_STRING="$vertag_256m"
        fi
        make BOARD=ruijie_rg-${{inputs.model}}-max VERSION=SP2 VARIANT=NONMBM MULTI_LAYOUT=0 FIXED_MTDPARTS=0 UBIMNG=1

        cp output/fip-mt7986_ruijie_rg-${{inputs.model}}*nonmbm*.bin ../outputs/nonmbm-yuzhii-fip-${{inputs.model}}.bin
        cp output/bl2-mt7986_ruijie_rg-${{inputs.model}}*nonmbm*.img ../outputs/nonmbm-yuzhii-bl2-${{inputs.model}}${{ env.suffix }}.img

    - name: Create release artifacts
      run: |
        echo "Creating release artifacts..."
        ls -l outputs
        mkdir release
        tar -czf release/bl2fip-${{inputs.model}}${{ env.suffix }}.tar.gz -C outputs .

        releasetag=$(date +"%Y%m%dT%H%M")_${{inputs.model}}
        echo "release_tag=$releasetag" >> $GITHUB_ENV

    - name: Release artifacts
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.release_tag }}
        allowUpdates: true
        artifacts: ./release/*
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          `bl2` and `fip` images for X60 New:  
          - `ubi-yuzhii-bl2-${{inputs.model}}${{ env.suffix }}.img`  
          - `ubi-yuzhii-fip-${{inputs.model}}.bin`  
          - `nonmbm-yuzhii-bl2-${{inputs.model}}${{ env.suffix }}.img`  
          - `nonmbm-yuzhii-fip-${{inputs.model}}.bin`  

          <br>  

          `bl2` build parameters: ${{ env.release_note }}  
          - `NAND_TYPE=${{ env.nand_type }} DRAM_USE_DDR4=0 DUAL_FIP=0 LOG_LEVEL=40`  
          - ubi: `UBI=1 OVERRIDE_UBI_START_ADDR=${{ env.ubi_addr }}`  
          - nonmbm: `NMBM=0`  

          `fip` build parameters:  
          - `VERSION=SP2 MULTI_LAYOUT=0 FIXED_MTDPARTS=0 UBIMNG=1`  
          - ubi: `VARIANT=UBI`  
          - nonmbm: `VARIANT=NONMBM`  

          <br>

          mtd `ubi` size: rest of the flash

          <br>  
          
          `bl2` & `fip` source code (yuzhii): https://github.com/Yuzhii0718/bl-mt798x-dhcpd  
