name: Test Build of BL2 & FIP for X60 New

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      flash_size:
        description: Flash size in megabytes (MB)
        default: "128"
        required: true

jobs:
  Build-bl2-fip:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v6

    - name: Create env variables 
      run: |
        echo "Create env variables based on flash size input..."
        echo "Flash size input: ${{ inputs.flash_size }}MB"
        if [ ${{ inputs.flash_size }} -eq 128 ]; then
          echo "nand type: spim:2k+64"
          echo "suffix=" | tee -a $GITHUB_ENV
        elif [ ${{ inputs.flash_size }} -eq 256 ]; then
          echo "nand type: spim:2k+128" 
          echo "suffix=_256m" | tee -a $GITHUB_ENV
          sed -i '/_NAND_TYPE_2K_/s/64/128/' atf-mtk/configs-*/mt7986_ruijie_rg-x60-new_defconfig
        else
          echo "Invalid flash size. Please enter either 128 or 256."
          exit 1
        fi

        echo "Setting source code versions..."
        echo "uboot_ver=uboot-mtk-20250711" | tee -a $GITHUB_ENV
        echo "atf_ver=atf-20260123" | tee -a $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu build-essential device-tree-compiler nodejs

        mkdir outputs

    - name: Build bl2 & fip for X60 New - UBI
      run: |
        echo "Building bl2 & fip for UBI variant..."
        git clone --depth 1 https://github.com/Yuzhii0718/bl-mt798x-dhcpd.git fip

        cd fip
        cp ../uboot-mtk/configs-fit/mt7986_ruijie_rg-x60-new_defconfig ${{ env.uboot_ver }}/configs-fit/
        cp ../atf-mtk/configs-fit/mt7986_ruijie_rg-x60-new_defconfig ${{ env.atf_ver }}/configs-fit/

        make BOARD=ruijie_rg-x60-new VERSION=SP2 VARIANT=UBOOTMOD MULTI_LAYOUT=0 FIXED_MTDPARTS=0 UBIMNG=1

        cp output/fip-mt7986_ruijie_rg-x60-new*fit*.bin ../outputs/ubi-yuzhii-fip-x60-new.bin
        cp output/bl2-mt7986_ruijie_rg-x60-new*fit*.bin ../outputs/ubi-yuzhii-bl2-x60-new${{ env.suffix }}.bin

    - name: Build bl2 & fip for X60 New - NONMBM
      run: |
        echo "Building bl2 & fip for NONMBM variant..."
        cd fip
        make clean && rm -rf output/*
        cp ../uboot-mtk/configs-nonmbm/mt7986_ruijie_rg-x60-new_defconfig ${{ env.uboot_ver }}/configs-nonmbm/
        cp ../atf-mtk/configs-nonmbm/mt7986_ruijie_rg-x60-new_defconfig ${{ env.atf_ver }}/configs-nonmbm/

        make BOARD=ruijie_rg-x60-new VERSION=SP2 VARIANT=NONMBM MULTI_LAYOUT=0 FIXED_MTDPARTS=0 UBIMNG=1

        cp output/fip-mt7986_ruijie_rg-x60-new*nonmbm*.bin ../outputs/nonmbm-yuzhii-fip-x60-new.bin
        cp output/bl2-mt7986_ruijie_rg-x60-new*nonmbm*.bin ../outputs/nonmbm-yuzhii-bl2-x60-new${{ env.suffix }}.bin

    - name: Upload bl2 and fip image
      uses: actions/upload-artifact@v7
      with:
        name: bl2fip-x60-new${{ env.suffix }}
        overwrite: true
        retention-days: 3
        path: outputs/*
