name: Test Build of BL2 & FIP for X60 New

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      flash_size:
        description: Flash size in megabytes (MB)
        default: "128"
        required: true

jobs:
  Build-bl2-fip:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v6

    - name: Create env variables based on flash size input
      run: |
        echo "Flash size input: ${{ inputs.flash_size }}MB"
        if [ ${{ inputs.flash_size }} -eq 128 ]; then
          echo "Flash size: 128MB"
          echo "nand_type=spim:2k+64" >> $GITHUB_ENV
          echo "suffix=" >> $GITHUB_ENV
        elif [ ${{ inputs.flash_size }} -eq 256 ]; then
          echo "Flash size: 256MB"
          echo "nand_type=spim:2k+128" >> $GITHUB_ENV
          echo "suffix=_256m" >> $GITHUB_ENV
        else
          echo "Invalid flash size. Please enter either 128 or 256."
          exit 1
        fi

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu build-essential \
        device-tree-compiler nodejs

        mkdir release

    - name: Build bl2 for X60 New - UBI
      run: |
        git clone -b mtksoc --depth 1 https://github.com/mtk-openwrt/arm-trusted-firmware.git atf

        cd atf
        make -f Makefile PLAT=mt7986 BOOT_DEVICE=spim-nand NAND_TYPE=${{ env.nand_type }} UBI=1 \
        OVERRIDE_UBI_START_ADDR=0x680000 DRAM_USE_DDR4=0 DUAL_FIP=0 LOG_LEVEL=40 bl2

        cp build/mt7986/release/bl2.img ../release/ubi-mtk-bl2-x60-new${{ env.suffix }}.img

    - name: Build bl2 for X60 New - NONMBM
      run: |
        cd atf
        make clean && rm -rf build/* 
        make -f Makefile PLAT=mt7986 BOOT_DEVICE=spim-nand NAND_TYPE=${{ env.nand_type }} NMBM=0 \
        DRAM_USE_DDR4=0 DUAL_FIP=0 LOG_LEVEL=40 bl2

        cp build/mt7986/release/bl2.img ../release/nonmbm-mtk-bl2-x60-new${{ env.suffix }}.img

    - name: Build fip for X60 New - UBI
      run: |
        git clone --depth 1 https://github.com/Yuzhii0718/bl-mt798x-dhcpd.git fip

        cd fip
        cp ../uboot-mtk/configs-fit/mt7986_ruijie_rg-x60-new_defconfig uboot-mtk-20250711/configs-fit/

        make BOARD=ruijie_rg-x60-new VERSION=SP2 VARIANT=UBOOTMOD MULTI_LAYOUT=0 FIXED_MTDPARTS=0 UBIMNG=1

        cp output/fip-mt7986_ruijie_rg-x60-new*fit*.bin ../release/ubi-yuzhii-fip-x60-new.bin

    - name: Build fip for X60 New - NONMBM
      run: |
        cd fip
        make clean && rm -rf output/*
        cp ../uboot-mtk/configs-nonmbm/mt7986_ruijie_rg-x60-new_defconfig uboot-mtk-20250711/configs-nonmbm/

        make BOARD=ruijie_rg-x60-new VERSION=SP2 VARIANT=NONMBM MULTI_LAYOUT=0 FIXED_MTDPARTS=0 UBIMNG=1

        cp output/fip-mt7986_ruijie_rg-x60-new*nonmbm*.bin ../release/nonmbm-yuzhii-fip-x60-new.bin

    - name: Upload bl2 and fip image
      uses: actions/upload-artifact@v7
      with:
        name: bl2fip-x60-new${{ env.suffix }}
        overwrite: true
        retention-days: 3
        path: release/*
