name: X30E Pro - Build BL2 & FIP

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build-bl2-fip:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu build-essential device-tree-compiler nodejs

        mkdir outputs

    - name: Build bl2 & fip for X30E Pro - NONMBM
      run: |
        git clone --depth 1 https://github.com/Yuzhii0718/bl-mt798x-dhcpd.git fip

        cd fip
        cp ../uboot-mtk/configs-nonmbm/mt7981_ruijie_rg-x30e-pro_defconfig uboot-mtk-20250711/configs-nonmbm/

        make BOARD=ruijie_rg-x30e-pro VERSION=SP2 VARIANT=NONMBM MULTI_LAYOUT=0 FIXED_MTDPARTS=0 UBIMNG=1

        cp output/bl2-mt7981_ruijie_rg-x30e-pro*nonmbm*.img ../outputs/nonmbm-yuzhii-bl2-x30e-pro.img
        cp output/fip-mt7981_ruijie_rg-x30e-pro*nonmbm*.bin ../outputs/nonmbm-yuzhii-fip-x30e-pro.bin

    - name: Create release artifacts
      run: |
        echo "Creating release artifacts..."
        ls -l outputs
        mkdir release
        tar -czf release/bl2fip-x30e-pro.tar.gz -C outputs .
        releasetag=$(date +"%Y%m%dT%H%M")
        echo "release_tag=$releasetag" >> $GITHUB_ENV

    - name: Release artifacts
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.release_tag }}
        allowUpdates: true
        artifacts: ./release/*
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          `bl2` and `fip` images for X30E Pro:  
          - `nonmbm-yuzhii-bl2-x30e-pro.img`  
          - `nonmbm-yuzhii-fip-x30e-pro.bin`  

          <br>  

          Build parameters:  
          - `VERSION=SP2 VARIANT=NONMBM MULTI_LAYOUT=0 FIXED_MTDPARTS=0 UBIMNG=1`  

          <br>  

          `bl2` & `fip` source code (yuzhii): https://github.com/Yuzhii0718/bl-mt798x-dhcpd  
